on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

name: Release

permissions:
  contents: write

jobs:
  if: >
        ${{ github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.ref =~ '^refs/tags/v[0-9]+\\.[0-9]+\\.[0-9]+(rc|pre)*[0-9]*$' }}
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          if [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            prerelease_flag=""
          else
            prerelease_flag="--prerelease"
          fi

          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              $prerelease_flag \
              --generate-notes
